### PR TITLE
Add Scribe-i18n to the full architecture diagram

### PR DESCRIPTION
**Pull request by Jag-Marcel**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
Adds Scribe-i18n as a localization file dependency for Scribe-iOS, Scribe-Android and Scribe-Desktop to the full architecture diagram.

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks @Jag-Marcel! @wkyoshida, could you give a review here?

**Review by andrewtavis — APPROVED** [review]
Just saw the thumbs up here from @wkyoshida :) Minor fix so that the path label has the same capitalization as the others. Thanks for this, @Jag-Marcel!

**Comment by wkyoshida** [comment]
Oh lol :laughing: I just opened the PR again now and saw @andrewtavis merge show up live

Apologies for the wait here, folks! :disappointed: Had couple pretty busy days lately. Was just going to suggest a minor adjustment as well, but I'll make a commit of my own for that. Thanks so much both @Jag-Marcel and @andrewtavis!!

**Comment by andrewtavis** [comment]
Sorry for the hasty merge, @wkyoshida! I read into it in my haste of brining in all of @Jag-Marcel's PRs :)

**Pull request merged**
